// Code generated by MockGen. DO NOT EDIT.
// Source: food-story/table-service/internal/adapter/cache (interfaces: RedisTableCacheInterface)
//
// Generated by this command:
//
//	mockgen -package mockcache -destination shared/mock/cache/table/redis.go food-story/table-service/internal/adapter/cache RedisTableCacheInterface
//

// Package mockcache is a generated GoMock package.
package mockcache

import (
	domain "food-story/table-service/internal/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRedisTableCacheInterface is a mock of RedisTableCacheInterface interface.
type MockRedisTableCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRedisTableCacheInterfaceMockRecorder
	isgomock struct{}
}

// MockRedisTableCacheInterfaceMockRecorder is the mock recorder for MockRedisTableCacheInterface.
type MockRedisTableCacheInterfaceMockRecorder struct {
	mock *MockRedisTableCacheInterface
}

// NewMockRedisTableCacheInterface creates a new mock instance.
func NewMockRedisTableCacheInterface(ctrl *gomock.Controller) *MockRedisTableCacheInterface {
	mock := &MockRedisTableCacheInterface{ctrl: ctrl}
	mock.recorder = &MockRedisTableCacheInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisTableCacheInterface) EXPECT() *MockRedisTableCacheInterfaceMockRecorder {
	return m.recorder
}

// DeleteCachedTable mocks base method.
func (m *MockRedisTableCacheInterface) DeleteCachedTable(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCachedTable", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCachedTable indicates an expected call of DeleteCachedTable.
func (mr *MockRedisTableCacheInterfaceMockRecorder) DeleteCachedTable(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCachedTable", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).DeleteCachedTable), key)
}

// ExtensionTTL mocks base method.
func (m *MockRedisTableCacheInterface) ExtensionTTL(sessionID uuid.UUID, newTTL time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtensionTTL", sessionID, newTTL)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtensionTTL indicates an expected call of ExtensionTTL.
func (mr *MockRedisTableCacheInterfaceMockRecorder) ExtensionTTL(sessionID, newTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtensionTTL", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).ExtensionTTL), sessionID, newTTL)
}

// GetCachedTable mocks base method.
func (m *MockRedisTableCacheInterface) GetCachedTable(sessionID uuid.UUID) (*domain.CurrentTableSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedTable", sessionID)
	ret0, _ := ret[0].(*domain.CurrentTableSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedTable indicates an expected call of GetCachedTable.
func (mr *MockRedisTableCacheInterfaceMockRecorder) GetCachedTable(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedTable", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).GetCachedTable), sessionID)
}

// GetCachedTableNumber mocks base method.
func (m *MockRedisTableCacheInterface) GetCachedTableNumber(key string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedTableNumber", key)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedTableNumber indicates an expected call of GetCachedTableNumber.
func (mr *MockRedisTableCacheInterfaceMockRecorder) GetCachedTableNumber(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedTableNumber", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).GetCachedTableNumber), key)
}

// GetCachedTableStatus mocks base method.
func (m *MockRedisTableCacheInterface) GetCachedTableStatus() ([]*domain.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedTableStatus")
	ret0, _ := ret[0].([]*domain.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedTableStatus indicates an expected call of GetCachedTableStatus.
func (mr *MockRedisTableCacheInterfaceMockRecorder) GetCachedTableStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedTableStatus", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).GetCachedTableStatus))
}

// GetTTL mocks base method.
func (m *MockRedisTableCacheInterface) GetTTL(sessionID uuid.UUID) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTTL", sessionID)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTTL indicates an expected call of GetTTL.
func (mr *MockRedisTableCacheInterfaceMockRecorder) GetTTL(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTTL", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).GetTTL), sessionID)
}

// IsCachedTableExist mocks base method.
func (m *MockRedisTableCacheInterface) IsCachedTableExist(sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCachedTableExist", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsCachedTableExist indicates an expected call of IsCachedTableExist.
func (mr *MockRedisTableCacheInterfaceMockRecorder) IsCachedTableExist(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCachedTableExist", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).IsCachedTableExist), sessionID)
}

// SetCachedTable mocks base method.
func (m *MockRedisTableCacheInterface) SetCachedTable(key string, table *domain.CurrentTableSession, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCachedTable", key, table, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCachedTable indicates an expected call of SetCachedTable.
func (mr *MockRedisTableCacheInterfaceMockRecorder) SetCachedTable(key, table, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCachedTable", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).SetCachedTable), key, table, ttl)
}

// SetCachedTableNumber mocks base method.
func (m *MockRedisTableCacheInterface) SetCachedTableNumber(key string, tableNumber int32, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCachedTableNumber", key, tableNumber, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCachedTableNumber indicates an expected call of SetCachedTableNumber.
func (mr *MockRedisTableCacheInterfaceMockRecorder) SetCachedTableNumber(key, tableNumber, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCachedTableNumber", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).SetCachedTableNumber), key, tableNumber, ttl)
}

// SetCachedTableStatus mocks base method.
func (m *MockRedisTableCacheInterface) SetCachedTableStatus(payload []domain.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCachedTableStatus", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCachedTableStatus indicates an expected call of SetCachedTableStatus.
func (mr *MockRedisTableCacheInterfaceMockRecorder) SetCachedTableStatus(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCachedTableStatus", reflect.TypeOf((*MockRedisTableCacheInterface)(nil).SetCachedTableStatus), payload)
}
