// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: health.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTimeNow = `-- name: GetTimeNow :one
select NOW() as "today"
`

func (q *Queries) GetTimeNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getTimeNow)
	var today pgtype.Timestamptz
	err := row.Scan(&today)
	return today, err
}

const health = `-- name: Health :one
SELECT 1 as "healthy"
`

func (q *Queries) Health(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, health)
	var healthy int32
	err := row.Scan(&healthy)
	return healthy, err
}
