// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: md_categories.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCategory = `-- name: ListCategory :many
SELECT id, "name", name_en as "nameEN", icon_name as "icon" FROM public.md_categories ORDER BY sort_order
`

type ListCategoryRow struct {
	ID     int64       `json:"id"`
	Name   string      `json:"name"`
	NameEN string      `json:"nameEN"`
	Icon   pgtype.Text `json:"icon"`
}

func (q *Queries) ListCategory(ctx context.Context) ([]*ListCategoryRow, error) {
	rows, err := q.db.Query(ctx, listCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListCategoryRow{}
	for rows.Next() {
		var i ListCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameEN,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
