// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: md_payment_statuses.sql

package database

import (
	"context"
)

const getPaymentStatusPending = `-- name: GetPaymentStatusPending :one
SELECT id FROM public.md_payment_statuses WHERE code = 'PENDING' LIMIT 1
`

func (q *Queries) GetPaymentStatusPending(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getPaymentStatusPending)
	var id int64
	err := row.Scan(&id)
	return id, err
}
