// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: md_session_extension_mode.sql

package database

import (
	"context"
)

const isSessionExtensionModeFree = `-- name: IsSessionExtensionModeFree :one
select COUNT(id) > 0 from public.md_session_extension_mode where id = $1 AND code = 'COMP_FREE' limit 1
`

func (q *Queries) IsSessionExtensionModeFree(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isSessionExtensionModeFree, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
