// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: md_session_extension_reason.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionExtensionModeByReasonCode = `-- name: GetSessionExtensionModeByReasonCode :one
select m.id, sem.id as "sessionExtensionModeID"
from public.md_session_extension_reason as m
         left join public.md_session_extension_mode as sem ON sem.code = m.mode_code
where m.code = $1 limit 1
`

type GetSessionExtensionModeByReasonCodeRow struct {
	ID                     int64       `json:"id"`
	SessionExtensionModeID pgtype.Int8 `json:"sessionExtensionModeID"`
}

func (q *Queries) GetSessionExtensionModeByReasonCode(ctx context.Context, code string) (*GetSessionExtensionModeByReasonCodeRow, error) {
	row := q.db.QueryRow(ctx, getSessionExtensionModeByReasonCode, code)
	var i GetSessionExtensionModeByReasonCodeRow
	err := row.Scan(&i.ID, &i.SessionExtensionModeID)
	return &i, err
}

const isSessionExtensionReasonExist = `-- name: IsSessionExtensionReasonExist :one
select id from public.md_session_extension_reason where id = $1 limit 1
`

func (q *Queries) IsSessionExtensionReasonExist(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, isSessionExtensionReasonExist, id)
	err := row.Scan(&id)
	return id, err
}

const listSessionExtensionReason = `-- name: ListSessionExtensionReason :many
select
    id,
    code,
    name,
    name_en as "nameEN",
    category,
    mode_code as "modeCode"
from public.md_session_extension_reason order by sort_order
`

type ListSessionExtensionReasonRow struct {
	ID       int64       `json:"id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	NameEN   string      `json:"nameEN"`
	Category pgtype.Text `json:"category"`
	ModeCode pgtype.Text `json:"modeCode"`
}

func (q *Queries) ListSessionExtensionReason(ctx context.Context) ([]*ListSessionExtensionReasonRow, error) {
	rows, err := q.db.Query(ctx, listSessionExtensionReason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListSessionExtensionReasonRow{}
	for rows.Next() {
		var i ListSessionExtensionReasonRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NameEN,
			&i.Category,
			&i.ModeCode,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
