// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_sequences.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrCreateOrderSequence = `-- name: GetOrCreateOrderSequence :one
INSERT INTO public.order_sequences (order_date, current_number)
VALUES ($1::date, 1)
ON CONFLICT (order_date) DO UPDATE
    SET current_number = order_sequences.current_number + 1
RETURNING current_number
`

func (q *Queries) GetOrCreateOrderSequence(ctx context.Context, orderDate pgtype.Date) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateOrderSequence, orderDate)
	var current_number int32
	err := row.Scan(&current_number)
	return current_number, err
}
