// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_sequences.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderSequence = `-- name: GetOrderSequence :one
INSERT INTO public.order_sequences (order_date, current_number)
VALUES ($1::date, 1)
ON CONFLICT (order_date) DO UPDATE
    SET current_number = order_sequences.current_number + 1
RETURNING current_number as "currentNumber"
`

func (q *Queries) GetOrderSequence(ctx context.Context, orderDate pgtype.Date) (int32, error) {
	row := q.db.QueryRow(ctx, getOrderSequence, orderDate)
	var currentNumber int32
	err := row.Scan(&currentNumber)
	return currentNumber, err
}
