// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_time_extension.sql

package database

import (
	"context"
)

const getDurationMinutesByProductID = `-- name: GetDurationMinutesByProductID :one
select duration_minutes from public.product_time_extension WHERE products_id = $1::bigint limit 1
`

func (q *Queries) GetDurationMinutesByProductID(ctx context.Context, productsID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getDurationMinutesByProductID, productsID)
	var duration_minutes int32
	err := row.Scan(&duration_minutes)
	return duration_minutes, err
}
