// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_extension.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionExtension = `-- name: CreateSessionExtension :one
insert into public.session_extension (id, session_id, requested_minutes, created_at, mode_id, reason_id)
values ($1, $2, $3, NOW(), $4, $5) RETURNING id
`

type CreateSessionExtensionParams struct {
	ID               int64       `json:"id"`
	SessionID        pgtype.UUID `json:"session_id"`
	RequestedMinutes int32       `json:"requested_minutes"`
	ModeID           pgtype.Int8 `json:"mode_id"`
	ReasonID         pgtype.Int8 `json:"reason_id"`
}

func (q *Queries) CreateSessionExtension(ctx context.Context, arg CreateSessionExtensionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSessionExtension,
		arg.ID,
		arg.SessionID,
		arg.RequestedMinutes,
		arg.ModeID,
		arg.ReasonID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
