// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TableSessionStatus string

const (
	TableSessionStatusActive  TableSessionStatus = "active"
	TableSessionStatusClosed  TableSessionStatus = "closed"
	TableSessionStatusExpired TableSessionStatus = "expired"
)

func (e *TableSessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TableSessionStatus(s)
	case string:
		*e = TableSessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TableSessionStatus: %T", src)
	}
	return nil
}

type NullTableSessionStatus struct {
	TableSessionStatus TableSessionStatus `json:"table_session_status"`
	Valid              bool               `json:"valid"` // Valid is true if TableSessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTableSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TableSessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TableSessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTableSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TableSessionStatus), nil
}

type MdCategory struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	NameEn    string           `json:"name_en"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type MdOrderStatus struct {
	ID        int64            `json:"id"`
	Code      string           `json:"code"`
	Name      string           `json:"name"`
	NameEn    string           `json:"name_en"`
	SortOrder int32            `json:"sort_order"`
	IsFinal   bool             `json:"is_final"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type MdTableStatus struct {
	ID        int64            `json:"id"`
	Code      string           `json:"code"`
	Name      string           `json:"name"`
	NameEn    string           `json:"name_en"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Order struct {
	ID          int64            `json:"id"`
	SessionID   pgtype.UUID      `json:"session_id"`
	TableID     int64            `json:"table_id"`
	StatusID    int64            `json:"status_id"`
	TotalAmount pgtype.Numeric   `json:"total_amount"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type OrderItem struct {
	ID            int64          `json:"id"`
	OrderID       int64          `json:"order_id"`
	ProductID     int64          `json:"product_id"`
	StatusID      int64          `json:"status_id"`
	ProductName   string         `json:"product_name"`
	ProductNameEn string         `json:"product_name_en"`
	Price         pgtype.Numeric `json:"price"`
	Quantity      int32          `json:"quantity"`
	Note          pgtype.Text    `json:"note"`
	// เวลาที่ทำอาหารเสร็จ
	PreparedAt pgtype.Timestamp `json:"prepared_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Product struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	NameEn      string           `json:"name_en"`
	Categories  int64            `json:"categories"`
	Description pgtype.Text      `json:"description"`
	Price       pgtype.Numeric   `json:"price"`
	IsAvailable bool             `json:"is_available"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Table struct {
	ID          int64            `json:"id"`
	TableNumber int32            `json:"table_number"`
	StatusID    int64            `json:"status_id"`
	Seats       int32            `json:"seats"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type TableSession struct {
	ID             int64                  `json:"id"`
	TableID        int64                  `json:"table_id"`
	SessionID      pgtype.UUID            `json:"session_id"`
	NumberOfPeople int32                  `json:"number_of_people"`
	Status         NullTableSessionStatus `json:"status"`
	StartedAt      pgtype.Timestamp       `json:"started_at"`
	ExpireAt       pgtype.Timestamp       `json:"expire_at"`
	EndedAt        pgtype.Timestamp       `json:"ended_at"`
}
