// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CreateTable(ctx context.Context, arg CreateTableParams) (int64, error)
	CreateTableStatus(ctx context.Context, arg CreateTableStatusParams) (int64, error)
	GetTotalPageQuickSearchTables(ctx context.Context, numberOfPeople int32) (int64, error)
	GetTotalPageSearchTables(ctx context.Context, arg GetTotalPageSearchTablesParams) (int64, error)
	Health(ctx context.Context) (int32, error)
	ListTableStatus(ctx context.Context) ([]*ListTableStatusRow, error)
	QuickSearchTables(ctx context.Context, arg QuickSearchTablesParams) ([]*QuickSearchTablesRow, error)
	SearchTables(ctx context.Context, arg SearchTablesParams) ([]*SearchTablesRow, error)
}

var _ Querier = (*Queries)(nil)
