// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: table_session.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTableSession = `-- name: CreateTableSession :one
INSERT INTO public.table_session
(id, table_id, number_of_people, status, started_at, expire_at, ended_at)
VALUES($1, $2, $3, 'active', NOW(), $4, NULL)
RETURNING session_id
`

type CreateTableSessionParams struct {
	ID             int64            `json:"id"`
	TableID        int64            `json:"table_id"`
	NumberOfPeople int32            `json:"number_of_people"`
	ExpireAt       pgtype.Timestamp `json:"expire_at"`
}

func (q *Queries) CreateTableSession(ctx context.Context, arg CreateTableSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTableSession,
		arg.ID,
		arg.TableID,
		arg.NumberOfPeople,
		arg.ExpireAt,
	)
	var session_id pgtype.UUID
	err := row.Scan(&session_id)
	return session_id, err
}
